[build]
  command   = "node build-bi.js"
  publish   = "site"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[headers]]
  for = "/lumen-data.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/lumen-app.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/bible-panneau.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
